-- ============================================================
-- 06_expand_hr.sql
-- Expand HR: more employees + PAYROLL, PERFORMANCE_REVIEWS,
-- JOB_HISTORY, ATTENDANCE
-- ============================================================

USE DATABASE CONVERSATIONAL_BI;
USE SCHEMA HR;
USE WAREHOUSE BI_ASSISTANT_WH;

-- ── DEPARTMENTS (expand to 10) ─────────────────────────────
-- CREATE OR REPLACE resets AUTOINCREMENT to 1..N each run so that child FKs
-- (EMPLOYEES.DEPT_ID, EXPENSES.DEPT_ID, etc.) populated via UNIFORM(1,N) resolve.
CREATE OR REPLACE TABLE DEPARTMENTS (
    DEPT_ID         INT AUTOINCREMENT PRIMARY KEY,
    DEPT_NAME       VARCHAR(100) NOT NULL,
    ANNUAL_BUDGET   DECIMAL(12,2),
    HEADCOUNT_BUDGET INT,
    COST_CENTER     VARCHAR(20),
    LOCATION        VARCHAR(100),
    MANAGER_ID      INT
);

INSERT INTO DEPARTMENTS (DEPT_NAME,ANNUAL_BUDGET,HEADCOUNT_BUDGET,COST_CENTER,LOCATION) VALUES
('Engineering',        4500000, 50, 'CC-ENG', 'San Francisco'),
('Sales',              3200000, 40, 'CC-SAL', 'New York'),
('Marketing',          2000000, 25, 'CC-MKT', 'New York'),
('Human Resources',    1200000, 15, 'CC-HR',  'Chicago'),
('Finance',            1800000, 20, 'CC-FIN', 'Chicago'),
('Operations',         2800000, 35, 'CC-OPS', 'San Francisco'),
('Customer Success',   1500000, 20, 'CC-CSX', 'Austin'),
('Product Management', 1000000, 12, 'CC-PM',  'San Francisco'),
('Legal',               800000,  8, 'CC-LEG', 'New York'),
('Data & Analytics',   1200000, 15, 'CC-DA',  'San Francisco');

-- ── EMPLOYEES (recreate with 200 rows via GENERATOR) ───────
CREATE OR REPLACE TABLE EMPLOYEES (
    EMP_ID      INT AUTOINCREMENT PRIMARY KEY,
    FIRST_NAME  VARCHAR(100),
    LAST_NAME   VARCHAR(100),
    EMAIL       VARCHAR(200),
    DEPT_ID     INT,
    JOB_TITLE   VARCHAR(150),
    JOB_LEVEL   VARCHAR(10),     -- L1-L7
    HIRE_DATE   DATE,
    SALARY      DECIMAL(10,2),
    BONUS_PCT   DECIMAL(5,2),
    STATUS      VARCHAR(20) DEFAULT 'Active',
    MANAGER_ID  INT
);

INSERT INTO EMPLOYEES (FIRST_NAME,LAST_NAME,EMAIL,DEPT_ID,JOB_TITLE,JOB_LEVEL,HIRE_DATE,SALARY,BONUS_PCT,STATUS)
SELECT
    CASE MOD(SEQ4(),25)
        WHEN 0 THEN 'James'    WHEN 1 THEN 'Sarah'    WHEN 2 THEN 'Michael' WHEN 3 THEN 'Emily'
        WHEN 4 THEN 'Daniel'   WHEN 5 THEN 'Jessica'  WHEN 6 THEN 'Robert'  WHEN 7 THEN 'Amanda'
        WHEN 8 THEN 'Chris'    WHEN 9 THEN 'Laura'    WHEN 10 THEN 'Kevin'  WHEN 11 THEN 'Nicole'
        WHEN 12 THEN 'Ryan'    WHEN 13 THEN 'Angela'  WHEN 14 THEN 'Tom'    WHEN 15 THEN 'Samantha'
        WHEN 16 THEN 'Brandon' WHEN 17 THEN 'Diana'   WHEN 18 THEN 'Marcus' WHEN 19 THEN 'Priya'
        WHEN 20 THEN 'Linda'   WHEN 21 THEN 'George'  WHEN 22 THEN 'Helen'  WHEN 23 THEN 'Victor'
        ELSE 'Catherine'
    END AS FIRST_NAME,
    CASE MOD(SEQ4(),20)
        WHEN 0 THEN 'Peterson' WHEN 1 THEN 'Chen'     WHEN 2 THEN 'Kumar'   WHEN 3 THEN 'Rodriguez'
        WHEN 4 THEN 'Park'     WHEN 5 THEN 'Lee'      WHEN 6 THEN 'Singh'   WHEN 7 THEN 'Foster'
        WHEN 8 THEN 'Wang'     WHEN 9 THEN 'Martinez' WHEN 10 THEN 'OBrien' WHEN 11 THEN 'Thompson'
        WHEN 12 THEN 'Davis'   WHEN 13 THEN 'Kim'     WHEN 14 THEN 'Baker'  WHEN 15 THEN 'Green'
        WHEN 16 THEN 'Cole'    WHEN 17 THEN 'Patel'   WHEN 18 THEN 'Hall'   ELSE 'Sharma'
    END AS LAST_NAME,
    'emp' || SEQ4() || '@company.com' AS EMAIL,
    UNIFORM(1,10,RANDOM()) AS DEPT_ID,
    CASE UNIFORM(1,8,RANDOM())
        WHEN 1 THEN 'Junior Analyst'      WHEN 2 THEN 'Analyst'
        WHEN 3 THEN 'Senior Analyst'      WHEN 4 THEN 'Lead'
        WHEN 5 THEN 'Manager'             WHEN 6 THEN 'Senior Manager'
        WHEN 7 THEN 'Director'            ELSE 'VP'
    END AS JOB_TITLE,
    CASE UNIFORM(1,7,RANDOM())
        WHEN 1 THEN 'L1' WHEN 2 THEN 'L2' WHEN 3 THEN 'L3' WHEN 4 THEN 'L4'
        WHEN 5 THEN 'L5' WHEN 6 THEN 'L6' ELSE 'L7'
    END AS JOB_LEVEL,
    DATEADD(DAY, -UNIFORM(90,2920,RANDOM()), CURRENT_DATE()) AS HIRE_DATE,
    ROUND(UNIFORM(55000,250000,RANDOM())::DECIMAL(10,2),2) AS SALARY,
    ROUND(UNIFORM(5,30,RANDOM())::DECIMAL(5,2),2)          AS BONUS_PCT,
    IFF(UNIFORM(1,10,RANDOM())=1,'Inactive','Active')      AS STATUS
FROM TABLE(GENERATOR(ROWCOUNT => 200));

-- ── JOB_HISTORY (300 rows — position changes over time) ────
CREATE OR REPLACE TABLE JOB_HISTORY (
    HISTORY_ID      INT AUTOINCREMENT PRIMARY KEY,
    EMP_ID          INT,
    FROM_DEPT_ID    INT,
    TO_DEPT_ID      INT,
    FROM_TITLE      VARCHAR(150),
    TO_TITLE        VARCHAR(150),
    FROM_SALARY     DECIMAL(10,2),
    TO_SALARY       DECIMAL(10,2),
    EFFECTIVE_DATE  DATE,
    CHANGE_REASON   VARCHAR(50)
);

INSERT INTO JOB_HISTORY (EMP_ID,FROM_DEPT_ID,TO_DEPT_ID,FROM_TITLE,TO_TITLE,FROM_SALARY,TO_SALARY,EFFECTIVE_DATE,CHANGE_REASON)
SELECT
    UNIFORM(1,200,RANDOM()) AS EMP_ID,
    UNIFORM(1,10,RANDOM())  AS FROM_DEPT_ID,
    UNIFORM(1,10,RANDOM())  AS TO_DEPT_ID,
    CASE UNIFORM(1,5,RANDOM()) WHEN 1 THEN 'Junior Analyst' WHEN 2 THEN 'Analyst' WHEN 3 THEN 'Senior Analyst' WHEN 4 THEN 'Lead' ELSE 'Manager' END AS FROM_TITLE,
    CASE UNIFORM(1,5,RANDOM()) WHEN 1 THEN 'Analyst' WHEN 2 THEN 'Senior Analyst' WHEN 3 THEN 'Lead' WHEN 4 THEN 'Manager' ELSE 'Senior Manager' END AS TO_TITLE,
    ROUND(UNIFORM(55000,180000,RANDOM())::DECIMAL(10,2),2) AS FROM_SALARY,
    ROUND(UNIFORM(65000,220000,RANDOM())::DECIMAL(10,2),2) AS TO_SALARY,
    DATEADD(DAY,-UNIFORM(90,1825,RANDOM()),CURRENT_DATE()) AS EFFECTIVE_DATE,
    CASE UNIFORM(1,5,RANDOM()) WHEN 1 THEN 'Promotion' WHEN 2 THEN 'Transfer' WHEN 3 THEN 'Restructure' WHEN 4 THEN 'Merit Raise' ELSE 'Lateral Move' END AS CHANGE_REASON
FROM TABLE(GENERATOR(ROWCOUNT => 300));

-- ── PAYROLL (200 employees x 24 months = 4800 rows) ────────
CREATE OR REPLACE TABLE PAYROLL (
    PAYROLL_ID      INT AUTOINCREMENT PRIMARY KEY,
    EMP_ID          INT,
    DEPT_ID         INT,
    PAY_PERIOD      DATE,          -- first of each month
    BASE_SALARY     DECIMAL(10,2),
    BONUS_AMOUNT    DECIMAL(10,2),
    OVERTIME_HOURS  DECIMAL(6,2),
    OVERTIME_PAY    DECIMAL(10,2),
    DEDUCTIONS      DECIMAL(10,2),
    NET_PAY         DECIMAL(10,2),
    PAY_STATUS      VARCHAR(20)    -- Processed, Pending
);

INSERT INTO PAYROLL (EMP_ID,DEPT_ID,PAY_PERIOD,BASE_SALARY,BONUS_AMOUNT,OVERTIME_HOURS,OVERTIME_PAY,DEDUCTIONS,NET_PAY,PAY_STATUS)
SELECT
    e.EMP_ID,
    e.DEPT_ID,
    DATEADD(MONTH, -m.MN, DATE_TRUNC('MONTH', CURRENT_DATE())) AS PAY_PERIOD,
    ROUND(e.SALARY / 12, 2)                                     AS BASE_SALARY,
    ROUND(IFF(m.MN IN (0,12), e.SALARY * e.BONUS_PCT / 100 / 2, 0), 2) AS BONUS_AMOUNT,
    ROUND(IFF(UNIFORM(1,5,RANDOM())=1, UNIFORM(2,20,RANDOM()), 0)::DECIMAL(6,2), 2) AS OVERTIME_HOURS,
    ROUND(IFF(UNIFORM(1,5,RANDOM())=1, UNIFORM(100,800,RANDOM()), 0)::DECIMAL(10,2), 2) AS OVERTIME_PAY,
    ROUND(e.SALARY / 12 * 0.22, 2)                              AS DEDUCTIONS,
    ROUND(e.SALARY / 12 * 0.78 + IFF(m.MN IN (0,12), e.SALARY * e.BONUS_PCT / 100 / 2, 0), 2) AS NET_PAY,
    IFF(m.MN = 0, 'Pending', 'Processed')                       AS PAY_STATUS
FROM EMPLOYEES e
CROSS JOIN (SELECT ROW_NUMBER() OVER (ORDER BY SEQ4()) - 1 AS MN FROM TABLE(GENERATOR(ROWCOUNT => 24))) m;

-- ── PERFORMANCE_REVIEWS (200 employees x 8 quarters = 1600) 
CREATE OR REPLACE TABLE PERFORMANCE_REVIEWS (
    REVIEW_ID       INT AUTOINCREMENT PRIMARY KEY,
    EMP_ID          INT,
    DEPT_ID         INT,
    REVIEW_PERIOD   VARCHAR(10),   -- e.g. 2024-Q1
    REVIEW_DATE     DATE,
    RATING          DECIMAL(3,1),  -- 1.0 to 5.0
    GOALS_MET_PCT   DECIMAL(5,2),
    REVIEWER_ID     INT,
    COMMENTS        VARCHAR(200)
);

INSERT INTO PERFORMANCE_REVIEWS (EMP_ID,DEPT_ID,REVIEW_PERIOD,REVIEW_DATE,RATING,GOALS_MET_PCT,REVIEWER_ID)
SELECT
    e.EMP_ID,
    e.DEPT_ID,
    YEAR(DATEADD(QUARTER,-q.QN,CURRENT_DATE())) || '-Q' || QUARTER(DATEADD(QUARTER,-q.QN,CURRENT_DATE())) AS REVIEW_PERIOD,
    DATEADD(QUARTER,-q.QN,CURRENT_DATE())       AS REVIEW_DATE,
    ROUND(UNIFORM(10,50,RANDOM())/10.0, 1)      AS RATING,
    ROUND(UNIFORM(50,100,RANDOM())::DECIMAL(5,2),2) AS GOALS_MET_PCT,
    UNIFORM(1,200,RANDOM())                     AS REVIEWER_ID
FROM EMPLOYEES e
CROSS JOIN (SELECT ROW_NUMBER() OVER (ORDER BY SEQ4()) - 1 AS QN FROM TABLE(GENERATOR(ROWCOUNT => 8))) q;

-- ── ATTENDANCE (200 employees x 104 weeks = ~20800 rows) ───
CREATE OR REPLACE TABLE ATTENDANCE (
    ATTENDANCE_ID   INT AUTOINCREMENT PRIMARY KEY,
    EMP_ID          INT,
    DEPT_ID         INT,
    WEEK_START_DATE DATE,
    DAYS_PRESENT    INT,           -- 0-5
    HOURS_WORKED    DECIMAL(6,2),
    LEAVE_DAYS      INT,
    LEAVE_TYPE      VARCHAR(30)    -- None, Annual, Sick, Public Holiday
);

INSERT INTO ATTENDANCE (EMP_ID,DEPT_ID,WEEK_START_DATE,DAYS_PRESENT,HOURS_WORKED,LEAVE_DAYS,LEAVE_TYPE)
SELECT
    e.EMP_ID,
    e.DEPT_ID,
    DATEADD(WEEK,-w.WN, DATE_TRUNC('WEEK',CURRENT_DATE())) AS WEEK_START_DATE,
    UNIFORM(3,5,RANDOM())        AS DAYS_PRESENT,
    ROUND(UNIFORM(30,45,RANDOM())::DECIMAL(6,2),2) AS HOURS_WORKED,
    IFF(UNIFORM(1,5,RANDOM())=1, UNIFORM(1,2,RANDOM()), 0) AS LEAVE_DAYS,
    CASE UNIFORM(1,4,RANDOM()) WHEN 1 THEN 'Annual' WHEN 2 THEN 'Sick' WHEN 3 THEN 'Public Holiday' ELSE 'None' END AS LEAVE_TYPE
FROM EMPLOYEES e
CROSS JOIN (SELECT ROW_NUMBER() OVER (ORDER BY SEQ4()) - 1 AS WN FROM TABLE(GENERATOR(ROWCOUNT => 104))) w;
